### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by georgyfarniev** [iyobo/koa-ts-controllers#1]
Hello. First of all, thanks for creating this package! It's really sad that https://github.com/typestack/routing-controllers/ is almost dead now and I was glad to see your project.  I just want to know about your plans for this project and if it's ready to use for serious application.

I want to keep things simple, that's why I want to avoid complicated things such as nest. everything I need is basic routing and decorator-based injections and validations, things that your library provides.

So, what is your plans about it? Will you continue develop it? Will you at least accept PR's?

Thanks 👍

**Comment by iyobo** [comment]
As a lover and user of Koa myself, I fully intend to develop this and keep it up to date.

I use this in all the REST APIs that I or any team I have technical leadership over builds.

In fact, the next minor release will have support for OpenAPI3 spec file generation.

EDIT: Thanks for creating those issues. I should have them resolved and a new patch pushed out this weekend! 👍
