### ISSUE TITLE
Should not bootstrapControllers be wraapped in async function

### ISSUE THREAD

**Issue by sirfak** [iyobo/koa-ts-controllers#10]
I am unable to call await  bootstrapControllers(app,{options...} it seems with the error that it needs to be wrapped in async function.

Is there any sample project i can have a look?

Thanks

**Comment by sirfak** [comment]
I am able to create one as this

// main.ts

const init = async () => {
  await bootstrapControllers(app, {...options}
}

.............


init();
app.listen(3000, () => {
  console.log("Koa started");
});

**Comment by iyobo** [comment]
You can also treat it like a promise.

bootstrapControllers(...).then(...).catch(...).

Though if you intend to use Koa, which this library is about, you should wrap your app initialization inside an async function i.e

```
(async function(){
   await bootstrapControllers(...)
})();
```
