### ISSUE TITLE
Defensive url append

### ISSUE THREAD

**Issue by anonrig** [iyobo/koa-ts-controllers#17]
Currently, the parent pth and the action.path are contacted directly in the following code:

https://github.com/iyobo/koa-ts-controllers/blob/master/src/util/generateRoutes.ts#L128

But if the parentPath is "/" and action.path is: "/config"

the output is "//config", but it should be "/config", didn't find an edge case to this but following code can fix this issue:

```
"/" + "//notemate/help".split('/').filter(i => i.length).join("/")
```

**Comment by iyobo** [comment]
Resolved and deployed in v1.5
