### ISSUE TITLE
Use API versioning on top level instead of controller decorator

### ISSUE THREAD

**Issue by georgyfarniev** [iyobo/koa-ts-controllers#2]
Hi. It would be nice to have option of creating version globally, not by picking specific controllers with @version() decorator. For example:

```js
await bootstrapControllers(app, {
    router,
    basePath: '/api',
    initBodyParser: true,
    boomifyErrors: true,
    versions:{
        1: './version1_controllers/**/*.ts',
        2: './version2_controllers/**/*.ts'
    }
});
```

Or just use custom controllers structure, not just list, but object with version prefixes similar to versions...

**Comment by iyobo** [comment]
@georgyfarniev the @Version() decorators satisfy situations where it makes sense to define the different endpoint handler versions in the same controller class, thus having granular control over version endpoints that are basically the same across versions and avoiding duplication.

I believe You can already achieve what you are requesting by globally disabling in-built apiVersioning and just manually inserting version indicator in controller base path i.e 
```
await bootstrapControllers(app, {
    router,
    basePath: '/api',
    initBodyParser: true,
    boomifyErrors: true,
    disableVersion: true
});

//----

@Controller('/v1/foo')
class FooControllerV1 {
...
}

@Controller('/v2/foo')
class FooControllerV2 {
...
}

```

**Comment by georgyfarniev** [comment]
@iyobo I think it’s enough time for now to solve all problems with different api versions. Thank you. Closing
