### ISSUE TITLE
Create roadmap

### ISSUE THREAD

**Issue by georgyfarniev** [iyobo/koa-ts-controllers#9]
Hi @iyobo, I think we need some roadmap to define project scope and features. The last one is necessary to prevent us from working on same issue simultaneously. I don’t have much time but I want to help with PR’s (if you want). Also I think it’s important to keep this project simple as now, but it need better documentation and existing features support. 

The problem of other frameworks such as nestjs is their complexity. Not all projects need all this features, but really most rest API needs features provided by this project, such as input validation and injection of parameters. 

I think this module has bright future after some polishing and popularization. 

Regards, George

**Comment by iyobo** [comment]
Done
